name: Go

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/carapace-sh/go:1.23.0
    steps:
      - name: deep clone
        uses: actions/checkout@v4
        with:
          repository: carapace-sh/carapace-bin
          fetch-depth: 0

      - name: fix git safe.directory
        run:  git config --global --add safe.directory '*'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: '~> v2'
          args: release --clean --skip announce,aur,chocolatey,docker,homebrew,ko,nfpm,nix,notarize,publish,sbom,scoop,sign,snapcraft,validate,winget
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install gh
        run: apt-get update && apt-get install -y gh

      - name: upload archives
        run: gh repo view
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
