name: Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    container: ghcr.io/carapace-sh/go:1.23.0
    steps:
      - name: shallow clone
        uses: actions/checkout@v4
        with:
          repository: carapace-sh/carapace-bin

      - name: fix git safe.directory
        run:  git config --global --add safe.directory '*'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: '~> v2'
          args: build --clean --skip validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
